export enum ActionType {
    ADD_USER = "ADD_USER",
    LOGIN_USER = "LOGIN_USER",
    REGISTER_CLIENT = "REGISTER_CLIENT",
    CURRENT_USER = "CURRENT_USER",
    EDIT_CLIENT = "EDIT_CLIENT",
    ST_ASSESSMENT = "ST_ASSESSMENT",
}